server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jingdong?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
logging:
  level:
    root: error
    com:
      woniu: debug
mybatis:
  type-aliases-package: com.woniu.jd.pojo.entity
  mapper-locations: classpath:mapper/*.xml