package com.woniu.orders.mbg.model;

import java.io.Serializable;

public class Orders implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.orderid
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private Integer orderid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.uname
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private String uname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pname
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.pprice
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private Float pprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.buycount
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private Integer buycount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders.describute
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private String describute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.orderid
     *
     * @return the value of orders.orderid
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public Integer getOrderid() {
        return orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.orderid
     *
     * @param orderid the value for orders.orderid
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public void setOrderid(Integer orderid) {
        this.orderid = orderid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.uname
     *
     * @return the value of orders.uname
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.uname
     *
     * @param uname the value for orders.uname
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public void setUname(String uname) {
        this.uname = uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pname
     *
     * @return the value of orders.pname
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pname
     *
     * @param pname the value for orders.pname
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.pprice
     *
     * @return the value of orders.pprice
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public Float getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.pprice
     *
     * @param pprice the value for orders.pprice
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public void setPprice(Float pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.buycount
     *
     * @return the value of orders.buycount
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public Integer getBuycount() {
        return buycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.buycount
     *
     * @param buycount the value for orders.buycount
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public void setBuycount(Integer buycount) {
        this.buycount = buycount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders.describute
     *
     * @return the value of orders.describute
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public String getDescribute() {
        return describute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders.describute
     *
     * @param describute the value for orders.describute
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    public void setDescribute(String describute) {
        this.describute = describute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders
     *
     * @mbg.generated Mon Jan 11 22:16:40 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", orderid=").append(orderid);
        sb.append(", uname=").append(uname);
        sb.append(", pname=").append(pname);
        sb.append(", pprice=").append(pprice);
        sb.append(", buycount=").append(buycount);
        sb.append(", describute=").append(describute);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}