package com.woniu.cacheb.entity;

public class Student {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_id
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private Integer stuId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_name
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private String stuName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_gender
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private String stuGender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_age
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private Integer stuAge;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_nation
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private String stuNation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_type
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private Integer stuType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_class
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private Integer stuClass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_tel
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private String stuTel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_native
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private String stuNative;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column student.stu_status
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    private String stuStatus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_id
     *
     * @return the value of student.stu_id
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public Integer getStuId() {
        return stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_id
     *
     * @param stuId the value for student.stu_id
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuId(Integer stuId) {
        this.stuId = stuId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_name
     *
     * @return the value of student.stu_name
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public String getStuName() {
        return stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_name
     *
     * @param stuName the value for student.stu_name
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuName(String stuName) {
        this.stuName = stuName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_gender
     *
     * @return the value of student.stu_gender
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public String getStuGender() {
        return stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_gender
     *
     * @param stuGender the value for student.stu_gender
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuGender(String stuGender) {
        this.stuGender = stuGender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_age
     *
     * @return the value of student.stu_age
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public Integer getStuAge() {
        return stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_age
     *
     * @param stuAge the value for student.stu_age
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuAge(Integer stuAge) {
        this.stuAge = stuAge;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_nation
     *
     * @return the value of student.stu_nation
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public String getStuNation() {
        return stuNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_nation
     *
     * @param stuNation the value for student.stu_nation
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuNation(String stuNation) {
        this.stuNation = stuNation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_type
     *
     * @return the value of student.stu_type
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public Integer getStuType() {
        return stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_type
     *
     * @param stuType the value for student.stu_type
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuType(Integer stuType) {
        this.stuType = stuType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_class
     *
     * @return the value of student.stu_class
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public Integer getStuClass() {
        return stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_class
     *
     * @param stuClass the value for student.stu_class
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuClass(Integer stuClass) {
        this.stuClass = stuClass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_tel
     *
     * @return the value of student.stu_tel
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public String getStuTel() {
        return stuTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_tel
     *
     * @param stuTel the value for student.stu_tel
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuTel(String stuTel) {
        this.stuTel = stuTel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_native
     *
     * @return the value of student.stu_native
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public String getStuNative() {
        return stuNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_native
     *
     * @param stuNative the value for student.stu_native
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuNative(String stuNative) {
        this.stuNative = stuNative;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column student.stu_status
     *
     * @return the value of student.stu_status
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public String getStuStatus() {
        return stuStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column student.stu_status
     *
     * @param stuStatus the value for student.stu_status
     *
     * @mbggenerated Fri Dec 25 13:13:36 CST 2020
     */
    public void setStuStatus(String stuStatus) {
        this.stuStatus = stuStatus;
    }
}