package com.woniu.smartremind.mbg.mapper;

import com.woniu.smartremind.mbg.model.Crime;
import com.woniu.smartremind.mbg.model.CrimeExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CrimeMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    long countByExample(CrimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int deleteByExample(CrimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int deleteByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int insert(Crime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int insertSelective(Crime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    List<Crime> selectByExample(CrimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    Crime selectByPrimaryKey(Integer zid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int updateByExampleSelective(@Param("record") Crime record, @Param("example") CrimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int updateByExample(@Param("record") Crime record, @Param("example") CrimeExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int updateByPrimaryKeySelective(Crime record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    int updateByPrimaryKey(Crime record);
}