package com.woniu.product;

import java.io.Serializable;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pid
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    private Integer pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pname
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    private String pname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.pprice
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    private Float pprice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.storecount
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    private Integer storecount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column product.describute
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    private String describute;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table product
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pid
     *
     * @return the value of product.pid
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pid
     *
     * @param pid the value for product.pid
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pname
     *
     * @return the value of product.pname
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public String getPname() {
        return pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pname
     *
     * @param pname the value for product.pname
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public void setPname(String pname) {
        this.pname = pname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.pprice
     *
     * @return the value of product.pprice
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public Float getPprice() {
        return pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.pprice
     *
     * @param pprice the value for product.pprice
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public void setPprice(Float pprice) {
        this.pprice = pprice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.storecount
     *
     * @return the value of product.storecount
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public Integer getStorecount() {
        return storecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.storecount
     *
     * @param storecount the value for product.storecount
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public void setStorecount(Integer storecount) {
        this.storecount = storecount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column product.describute
     *
     * @return the value of product.describute
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public String getDescribute() {
        return describute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column product.describute
     *
     * @param describute the value for product.describute
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    public void setDescribute(String describute) {
        this.describute = describute;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product
     *
     * @mbg.generated Mon Jan 11 21:14:38 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", pid=").append(pid);
        sb.append(", pname=").append(pname);
        sb.append(", pprice=").append(pprice);
        sb.append(", storecount=").append(storecount);
        sb.append(", describute=").append(describute);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}