package com.woniu.cachea.entity;

import java.io.Serializable;

public class Stu implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.id
     *
     * @mbggenerated Thu Dec 24 23:44:47 CST 2020
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column stu.name
     *
     * @mbggenerated Thu Dec 24 23:44:47 CST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.id
     *
     * @return the value of stu.id
     *
     * @mbggenerated Thu Dec 24 23:44:47 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.id
     *
     * @param id the value for stu.id
     *
     * @mbggenerated Thu Dec 24 23:44:47 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column stu.name
     *
     * @return the value of stu.name
     *
     * @mbggenerated Thu Dec 24 23:44:47 CST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column stu.name
     *
     * @param name the value for stu.name
     *
     * @mbggenerated Thu Dec 24 23:44:47 CST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}