# FebsProperties
base:
  auto-open-browser: true
  shiro:
    session-timeout: PT86400s
    cookie-timeout: PT604800s
    anon-url: /test/**,/febs/**,/img/**,/layui/**,/json/**,/images/captcha,/register,/actuator/**
    login-url: /login
    success-url: /index
    logout-url: /logout
    unauthorized-url: /unauthorized
  max-batch-insertNum: 300
  code:
    time: 120
    type: png
    width: 115
    height: 42
    length: 4
    char-type: 2
  swagger:
    base-package: cc.zy.base
    title: FEBS Shiro API
    description: FEBS Shiro API Document.
    version: 2.0
    author: zy
    url: https://zy.cc
    email: 250196904@qq.com
    license: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html