server:
  port: 9000
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud_orders?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  application:
    name: microorders
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
    sentinel:
      transport:
        port: 9999
        dashboard: localhost:8080
      filter:
        enabled: false
service:
  product_url: http://microproduct
logging:
  level:
    root: error
    com:
      woniu:
        orders: debug
feign:
  sentinel:
    enabled: true