package com.woniu.smartremind.mbg.model;

import java.io.Serializable;

public class Crime implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crime.zid
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    private Integer zid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crime.crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    private String crime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crime.simplecode
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    private String simplecode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column crime.fullcode
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    private String fullcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crime.zid
     *
     * @return the value of crime.zid
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public Integer getZid() {
        return zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crime.zid
     *
     * @param zid the value for crime.zid
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public void setZid(Integer zid) {
        this.zid = zid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crime.crime
     *
     * @return the value of crime.crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public String getCrime() {
        return crime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crime.crime
     *
     * @param crime the value for crime.crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public void setCrime(String crime) {
        this.crime = crime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crime.simplecode
     *
     * @return the value of crime.simplecode
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public String getSimplecode() {
        return simplecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crime.simplecode
     *
     * @param simplecode the value for crime.simplecode
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public void setSimplecode(String simplecode) {
        this.simplecode = simplecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column crime.fullcode
     *
     * @return the value of crime.fullcode
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public String getFullcode() {
        return fullcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column crime.fullcode
     *
     * @param fullcode the value for crime.fullcode
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    public void setFullcode(String fullcode) {
        this.fullcode = fullcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table crime
     *
     * @mbg.generated Sat Jan 09 15:45:57 CST 2021
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", zid=").append(zid);
        sb.append(", crime=").append(crime);
        sb.append(", simplecode=").append(simplecode);
        sb.append(", fullcode=").append(fullcode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}